apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  postgres-songdb-user: cG9zdGdyZXM=
  postgres-songdb-password: cG9zdGdyZXM=
  postgres-resourcedb-user: cG9zdGdyZXM=
  postgres-resourcedb-password: cG9zdGdyZXM=