apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.name" . }}-db-config  # Changed name
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  POSTGRES_DB: "postgres"
  init.sql: |
    CREATE TABLE IF NOT EXISTS resources (
      id serial NOT NULL,
      blob bytea,
      PRIMARY KEY (id)
    );