apiVersion: v1
kind: ConfigMap
metadata:
  name: resources-db-config
  namespace: {{ .Values.namespace }}
  labels:
    app: resources-db
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  POSTGRES_DB: "postgres"
  init.sql: |
    CREATE TABLE IF NOT EXISTS resources (
      id serial NOT NULL,
      blob bytea,
      PRIMARY KEY (id)
    );