apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.name" . }}-songs-config  # Changed name
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  POSTGRES_DB: "postgres"
  init.sql: |
    CREATE SEQUENCE IF NOT EXISTS songs_seq START WITH 1 INCREMENT BY 50;
    CREATE TABLE IF NOT EXISTS songs (
      id integer NOT NULL,
      resource_id integer NOT NULL UNIQUE,
      album varchar(255),
      artist varchar(255),
      length varchar(255),
      name varchar(255),
      year varchar(255),
      genre varchar(255),
      PRIMARY KEY (id)
    );