apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  namespace: k8s-program
  labels:
    app: eureka-service  # Consistent with your previous configs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service  # Must match labels applied to pod template
  template:
    metadata:
      labels:
        app: eureka-service  # Pod-specific label
    spec:
      containers:
        - name: eureka-server-container
          image: kristevsm/eureka-server
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: k8s-program
spec:
  selector:
    app: eureka-service  # This must also match Deployment's label
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761