apiVersion: v1
kind: ConfigMap
metadata:
  name: songsdb-init
  namespace: k8s-program
data:
  init.sql: |
    CREATE SEQUENCE IF NOT EXISTS songs_seq START WITH 1 INCREMENT BY 50;
    CREATE TABLE IF NOT EXISTS songs (
      id integer NOT NULL,
      resource_id integer NOT NULL UNIQUE,
      album varchar(255),
      artist varchar(255),
      length varchar(255),
      name varchar(255),
      year varchar(255),
      PRIMARY KEY (id)
    );

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resourcesdb-init
  namespace: k8s-program
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS resources (
      id serial NOT NULL,
      blob bytea,
      PRIMARY KEY (id)
    );