apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-ms-deployment
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resources-ms
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: resources-ms
    spec:
      containers:
        - name: resources-ms
          image: kristevsm/resource-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: RESOURCES_MS_PORT
              value: "8080"
            - name: RESOURCES_DB_URL
              value: "resources-db"
            - name: RESOURCES_DB_PORT
              value: "5432"
            - name: EUREKA_URI
              value: "eureka-service"
            - name: ENABLE_EUREKA_CLIENT
              value: "true"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service.k8s-program.svc.cluster.local:8761/eureka/"
            - name: SONGS_MS_URL
              value: "http://songs-ms"
            - name: SONGS_MS_PORT
              value:
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 20
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: resources-ms
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: resources-ms
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080