apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resources-db-pvc
  namespace: k8s-program
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi