apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-ms-deployment
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: songs-ms
  template:
    metadata:
      labels:
        app: songs-ms
    spec:
      containers:
        - name: songs-ms
          image: kristevsm/song-service
          ports:
            - containerPort: 8081
          env:
            - name: SONGS_MS_PORT
              value: "8081"
            - name: SONGS_DB_URL
              value: "songs-db"
            - name: SONGS_DB_PORT
              value: "5432"
            - name: EUREKA_URI
              value: "eureka-service"
            - name: ENABLE_EUREKA_CLIENT
              value: "true"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service.k8s-program.svc.cluster.local:8761/eureka/"

---
apiVersion: v1
kind: Service
metadata:
  name: songs-ms
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: songs-ms
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081